Add CMake support
alicevision/vlfeat pull request #1
Opened 2022-09-27 12:26 UTC by p12tic

This adds CMakeLists.txt from vcpkg. The project compiles locally, I haven't yet tested it with AliceVision. I will add AliceVision support in a subsequent PR.

2022-09-27 12:26 UTC, p12tic commented
@simogasp We should probably have `av_develop` in this repository too.

2022-09-27 16:59 UTC, simogasp commented
> @simogasp We should probably have `av_develop` in this repository too.

done, it's the default branch now and I changed the target branch of this PR as well

2022-09-27 17:17 UTC, simogasp requested changes
Thanks for the PR!
I left some comments

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +project (vlfeat)
```suggestion
project (vlfeat LANGUAGES C VERSION 0.9.21)
```
The latest tag 0.9.21 points at the latest commit on the master branch, so I guess we can start from there,

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +if(ENABLE_OPENMP)
I'd add an option like this at the beginning
```cmake
option(VLFEAT_ENABLE_OPENMP "Enable OpenMP optimization" ON)
```
the `VLFEAT_` is just to avoid ambiguities

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
I think we can remove this if we link to the provided target `OpenMP::OpenMP_C`

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +if(USE_SSE)
same here, maybe add an option at the beginning
```cmake
option(VLFEAT_USE_SSE "Enable SSE optimizations" ON)
option(VLFEAT_USE_AVX "Enable AVX optimization" ON)
```

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +target_compile_options(vl PRIVATE ${OpenMP_C_FLAGS})
I think we can replace this with 
```suggestion
if(VLFEAT_ENABLE_OPENMP)
    target_link_libraries(vl PRIVATE OpenMP::OpenMP_C)
endif()
```
that should import everything is needed, i think.
I haven't checked, but unless openmp is used in some hpp it should be ok to set it as `PRIVATE`. Can you confirm?

2022-09-27 17:17 UTC, simogasp commented on CMakeLists.txt
> +)
It's better to add the version file as well
```cmake
include(CMakePackageConfigHelpers)

set(version_config "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake")

write_basic_package_version_file("${version_config}"
                                 COMPATIBILITY SameMajorVersion)

install(FILES ${version_config}
        DESTINATION "${INSTALL_CMAKE_DIR}")
```

2022-09-30 16:58 UTC, p12tic commented on CMakeLists.txt
> +target_compile_options(vl PRIVATE ${OpenMP_C_FLAGS})
Thanks, this makes sense. We can make it private, indeed.

2022-09-30 16:58 UTC, p12tic commented on CMakeLists.txt
> +target_compile_options(vl PRIVATE ${OpenMP_C_FLAGS})
Fixed now.

2022-09-30 17:00 UTC, p12tic commented on CMakeLists.txt
> +  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
Yes, this is oversight from my refactoring. Fixed now.

2022-09-30 17:00 UTC, p12tic commented on CMakeLists.txt
> +if(USE_SSE)
Fixed now, thanks.

2022-09-30 17:01 UTC, p12tic commented on CMakeLists.txt
> +if(ENABLE_OPENMP)
Fixed now, thanks.

2022-09-30 17:01 UTC, p12tic commented on CMakeLists.txt
> +project (vlfeat)
Fixed now, thanks.

2022-09-30 17:03 UTC, p12tic commented on CMakeLists.txt
> +)
Fixed now, thanks.

2022-09-30 17:13 UTC, p12tic commented
@simogasp I have fixed all issues that you've identified. Note, that I disable OpenMP support because the current code is broken and needs investigation on whether the simple compile issues I've seen are the only ones and there isn't more significant bitrot.

2022-10-08 01:34 UTC, p12tic commented
@simogasp Just a friendly ping :-)

2022-10-09 13:36 UTC, merged

2022-10-09 13:37 UTC, simogasp commented
thanks for the reminder, I've forgotten